schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "Industrial_AOV_Connector"
version = "1.1.1"
name = "Industrial AOV Connector"
tagline = "Auto generate outputs for advanced compositing"
maintainer = "Roland Vyens"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional: add-ons can list which resources they will require:
# * "files" (for access of any filesystem operations)
# * "network" (for internet access)
# * "camera" (to capture photos and videos)
# * "microphone" (to capture audio)
permissions = ["files"]

# Optional link to documentation, support, source files, etc
website = "https://github.com/RolandVyens/Industrial-AOV-Connector"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Compositing", "Import-Export", "Pipeline", "Render"]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later",
]
# Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]