# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) Roland Vyens
"""Addon preferences for Industrial AOV Connector."""

import bpy
from bpy.types import AddonPreferences
from bpy.props import StringProperty, BoolProperty, FloatProperty, IntProperty


class IDS_AddonPrefs(AddonPreferences):
    # this must match the add-on name, use '__package__'
    # when defining this in a submodule of a python package.
    bl_idname = __package__.rsplit(".", 1)[0]  # Get parent package name

    Denoise_Col: BoolProperty(
        name="Denoise DiffCol / GlossCol / TransCol",
        description="Denoise DiffCol / GlossCol / TransCol (The flat color aovs), may increase divide precision",
        default=True,
    )  # type: ignore
    Use_Old_Layer_Naming: BoolProperty(
        name="Use Old EXR Layer Naming Convention",
        description="Use old EXR layer naming which is the same with 2.4.x below. The new layer naming is easier to read in nuke",
        default=False,
    )  # type: ignore
    Put_Default_To_trash_output: BoolProperty(
        name="Default useless renders gather",
        description='Auto change blender default render output path to "trash_output" subfolder, for convenient dump later',
        default=False,
    )  # type: ignore
    Show_QuickDel: BoolProperty(
        name="Show useless renders clean button",
        description='Show "Delete Useless Default Renders" button in Output Tools, for quickly delete "trash_output"',
        default=False,
    )  # type: ignore
    Only_Create_Enabled_Viewlayer: BoolProperty(
        name="Only Create Nodes For Enabled Viewlayers",
        description='Do not create nodes for viewlayers which their "Use For Rendering" checkbox is off',
        default=True,
    )  # type: ignore
    Use_Icon_Only_Preference_Button: BoolProperty(
        name="Use Icon-Only Preference Button",
        description="Use Icon-Only Style Preference Button",
        default=False,
    )  # type: ignore
    Preference_Button_On_The_Right: BoolProperty(
        name="Put Preference Button On The Right Of The Top Bar",
        description="Put Preference Button On The Right Of The Top Bar",
        default=True,
    )  # type: ignore
    Preference_Button_Show_Alert: BoolProperty(
        name="Display Preference Button As Alert Color",
        description="Display Preference Button As Alert Color",
        default=True,
    )  # type: ignore
    UI_Show_In_Comp: BoolProperty(
        name="Show UI In Compositor N Panel",
        description="If enabled, show UI in compositor N panel in addition to the property panel",
        default=False,
    )  # type: ignore
    Auto_Data_Sample: BoolProperty(
        name="Auto Optimize Sample Count For Data Layers",
        description="If enabled, Data Layers will get sample count override when generating nodes, for faster rendering",
        default=False,
    )  # type: ignore
    Arrange_Scale_Param: FloatProperty(
        name="Node Interval Scale When Arranging",
        description="Scale of node interval when arranging node, fix too wide node interval and space consumption. this is a compensation for system-wide UI scaling, for example My Windows uses a 1.5x scale, set this to 0.67 will generate proper nodetree",
        default=1.0,
        min=0.1,
        max=10.0,
        precision=2,
    )  # type: ignore
    Custom_Data_Sample: IntProperty(
        name="Sample Count Used For Data Layers",
        description="This value will be used for 'Auto Optimize Sample Count For Data Layers'",
        default=10,
        min=1,
        max=4096,
        step=1,
    )  # type: ignore
    Custom_Suffix: StringProperty(
        name="Custom Name Suffix",
        description='You can add custom text and preset to the file name generated by Industrial AOV Connector, for example use # to customize frame number digits. You can also use $scene$, $file$, $camera$, $version$ as preset that can be automatically changed to actual names when rendering ($version$ expects there is a "v001" style version number at the last of your blend file name). A good example is $scene$_$version$_###',
        default="####",
        maxlen=100,
    )  # type: ignore
    Horizontal_DATA_Arrange: BoolProperty(
        name="Horizontal DATA Layer Arrangement",
        description="In advanced mode, arrange DATA layers to the right of RGBA layers instead of below them",
        default=True,
    )  # type: ignore

    def draw(self, context):
        layout = self.layout
        box1 = layout.box()
        box1.label(text="Core Function:", icon="MODIFIER_ON")
        box1.prop(self, "Denoise_Col")
        box1.prop(self, "Use_Old_Layer_Naming")
        box1.prop(self, "Only_Create_Enabled_Viewlayer")
        box1.prop(self, "Auto_Data_Sample")
        if self.Auto_Data_Sample is True:
            box1.prop(self, "Custom_Data_Sample")
        box1.prop(self, "Custom_Suffix")
        box1.prop(self, "Arrange_Scale_Param", slider=False)
        box1.prop(self, "Horizontal_DATA_Arrange")
        box2 = layout.box()
        box2.label(text="Output Tools:", icon="MODIFIER_ON")
        box2.prop(self, "Put_Default_To_trash_output")
        box2.prop(self, "Show_QuickDel")
        box3 = layout.box()
        box3.label(text="Appearance:", icon="MODIFIER_ON")
        box3.prop(self, "UI_Show_In_Comp")
        box3.prop(self, "Use_Icon_Only_Preference_Button")
        box3.prop(self, "Preference_Button_On_The_Right")
        box3.prop(self, "Preference_Button_Show_Alert")
