# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) Roland Vyens
"""Basic operators for Industrial AOV Connector."""

import bpy
import os
import shutil

from ..handy_functions import (
    BlenderCompat,
    CompositorHelper,
    DataLayerHelper,
    has_subfolder,
)
from ..renderpath_preset import TokenReplacer
from ..constants import TRASH_OUTPUT_FOLDER



class Compositor_OT_enable_use_nodes(bpy.types.Operator):
    bl_idname = "compositor.use_nodes"
    bl_label = "Use Nodes"
    bl_description = "Turn on use nodes"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        CompositorHelper.enable(bpy.context.scene)
        return {"FINISHED"}


class IDS_OT_Turn_Denoise(bpy.types.Operator):
    bl_idname = "rendering.use_denoise_passes"
    bl_label = "Turn On Denoise For All Layers"
    bl_description = "Turn on denoise for all viewlayers"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        if bpy.context.scene.render.engine == "CYCLES":
            for viewlayer in bpy.context.scene.view_layers:
                viewlayer.cycles.denoising_store_passes = True

        return {"FINISHED"}


class IDS_OT_CloudMode(bpy.types.Operator):
    bl_idname = "compositor.cloudmodeids"
    bl_label = "Renderfarm Prepare"
    bl_description = "Toggle: Replace naming presets for render farm / Restore original paths"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        replacer = TokenReplacer()
        if context.scene.IDS_CloudModeActive:
            replacer.restore()
            context.scene.IDS_CloudModeActive = False
            self.report(
                {"INFO"}, bpy.app.translations.pgettext("Restored all naming presets")
            )
        else:
            replacer.replace()
            context.scene.IDS_CloudModeActive = True
            self.report(
                {"INFO"}, bpy.app.translations.pgettext("Pre-replaced all naming presets")
            )

        return {"FINISHED"}


class IDS_OT_Delete_Trash(bpy.types.Operator):
    bl_idname = "render.delete_trashoutput"
    bl_label = "Delete Useless Default Renders"
    bl_description = "Delete the folder called 'trash_output' which contains the default render of blender, safe to perform because valid output paths generated by the addon will always locate out of the 'trash_output' folder"
    bl_options = {"REGISTER"}

    @classmethod
    def poll(cls, context):
        preferences = bpy.context.preferences
        addon_prefs = preferences.addons[BlenderCompat.addon_package].preferences

        return addon_prefs.Show_QuickDel

    def execute(self, context):
        current_render_path = bpy.context.scene.render.filepath
        trash_folder_pattern = f"{TRASH_OUTPUT_FOLDER}\\\\"
        if (
            trash_folder_pattern in current_render_path
            and os.path.exists(current_render_path)
            and has_subfolder(current_render_path) is False
        ):
            shutil.rmtree(current_render_path)
            self.report({"INFO"}, bpy.app.translations.pgettext("Deleted"))
        elif (
            trash_folder_pattern in current_render_path
            and os.path.exists(current_render_path)
            and has_subfolder(current_render_path) is True
        ):
            self.report(
                {"WARNING"},
                "Danger file detected, interrupted",
            )
        else:
            self.report(
                {"INFO"},
                bpy.app.translations.pgettext("There is no trash_output folder"),
            )

        return {"FINISHED"}


class IDS_OT_Set_Material_AOV(bpy.types.Operator):
    bl_idname = "scene.setmaterialaov"
    bl_label = "Auto Set Shader AOV"
    bl_description = "Auto gather and set shader AOV for all viewlayers"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        DataLayerHelper.auto_set_aov()

        return {"FINISHED"}
