# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) Roland Vyens
"""Tree building operators for Industrial AOV Connector."""

import bpy

from ..handy_functions import auto_data_sample, update_data_sample
from ..path_modify_v2 import origin_render_path_change_loc
from ..core import node_builder


def get_addon_package():
    return __package__.rsplit(".", 1)[0]


class IDS_OT_Make_Tree(bpy.types.Operator):
    bl_idname = "compositor.make_tree"
    bl_label = "Cook Nodetree"
    bl_description = "make connector nodes in compositor"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        if (
            bpy.context.scene.IDS_AdvMode is True
            and bpy.context.scene.IDS_UseDATALayer is True
        ):
            node_builder.auto_connect_adv()
            auto_data_sample()
        else:
            node_builder.auto_connect()
        node_builder.arrange_All()
        node_builder.auto_rename()
        origin_render_path_change_loc()
        self.report({"INFO"}, bpy.app.translations.pgettext("All Outputs Updated"))

        return {"FINISHED"}


class IDS_OT_Update_Tree(bpy.types.Operator):
    bl_idname = "compositor.update_tree"
    bl_label = "Update Current Viewlayer"
    bl_description = "only update current viewlayer's connector nodes"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        if (
            bpy.context.scene.IDS_AdvMode is True
            and bpy.context.scene.IDS_UseDATALayer is True
        ):
            node_builder.update_connect_adv()
            update_data_sample()
        else:
            node_builder.update_connect()
        node_builder.arrange_All()
        node_builder.auto_rename()
        origin_render_path_change_loc()
        self.report(
            {"INFO"}, bpy.app.translations.pgettext("Viewlayer Outputs Updated")
        )

        return {"FINISHED"}


class IDS_OT_Arr_Tree(bpy.types.Operator):
    bl_idname = "compositor.arr_tree"
    bl_label = "Arrange Connector Nodes"
    bl_description = "arrange nodes generated by this plugin"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        node_builder.frame_DATA()
        node_builder.auto_arrange_viewlayer()
        node_builder.auto_arr_denoisenode()
        node_builder.auto_arr_outputnode()
        node_builder.auto_arr_mathnode()
        self.report({"INFO"}, bpy.app.translations.pgettext("Arrange finished"))

        return {"FINISHED"}
