# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) Roland Vyens
"""Tree building operators for Industrial AOV Connector."""

import bpy

from ..handy_functions import DataLayerHelper, BlenderCompat
from ..path_modify_v2 import PathManager
from ..core.node_builder import NodeConnector, NodeArranger


class IDS_OT_Make_Tree(bpy.types.Operator):
    bl_idname = "compositor.make_tree"
    bl_label = "Cook Nodetree"
    bl_description = "make connector nodes in compositor"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        connector = NodeConnector()
        arranger = NodeArranger()
        
        if (
            bpy.context.scene.IDS_AdvMode is True
            and bpy.context.scene.IDS_UseDATALayer is True
        ):
            connector.connect_all_adv()
            DataLayerHelper.auto_sample()
        else:
            connector.connect_all()
        
        arranger.arrange_all()
        arranger.rename_outputs()
        PathManager().move_to_trash_output()
        self.report({"INFO"}, bpy.app.translations.pgettext("All Outputs Updated"))

        return {"FINISHED"}


class IDS_OT_Update_Tree(bpy.types.Operator):
    bl_idname = "compositor.update_tree"
    bl_label = "Update Current Viewlayer"
    bl_description = "only update current viewlayer's connector nodes"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        connector = NodeConnector()
        arranger = NodeArranger()
        
        if (
            bpy.context.scene.IDS_AdvMode is True
            and bpy.context.scene.IDS_UseDATALayer is True
        ):
            connector.connect_current_adv()
            DataLayerHelper.update_sample()
        else:
            connector.connect_current()
        
        arranger.arrange_all()
        arranger.rename_outputs()
        PathManager().move_to_trash_output()
        self.report(
            {"INFO"}, bpy.app.translations.pgettext("Viewlayer Outputs Updated")
        )

        return {"FINISHED"}


class IDS_OT_Arr_Tree(bpy.types.Operator):
    bl_idname = "compositor.arr_tree"
    bl_label = "Arrange Connector Nodes"
    bl_description = "arrange nodes generated by this plugin"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        arranger = NodeArranger()
        
        arranger.frame_data_layers()
        arranger.arrange_viewlayers()
        arranger.arrange_denoise()
        arranger.arrange_outputs()
        arranger.arrange_math()
        
        # Horizontal DATA arrangement if enabled
        preferences = bpy.context.preferences
        addon_prefs = preferences.addons[BlenderCompat.addon_package].preferences
        if addon_prefs.Horizontal_DATA_Arrange and bpy.context.scene.IDS_AdvMode:
            arranger.arrange_data_horizontal()
        
        self.report({"INFO"}, bpy.app.translations.pgettext("Arrange finished"))

        return {"FINISHED"}
